name: mac-m1-13
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: warp-macos-15-arm64-6x
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
